### ISSUE TITLE
Interactive mode breaks input of other commands/arguments in 3.0.0-dev-00003

### ISSUE THREAD

**Issue by JohannesDeml** [adambajguz/Typin#108]
**Describe the bug**
In the latest nuget package (`3.0.0-dev-00003`) the option to add commands or arguments before orr after `[interactive]` does not work. commands seem to be completely ignored, while arguments like `-h` stop the interactive mode.

**To Reproduce**
1. Run InteractiveModeExample with `[interactive] -h` as described in the wikie
2. Expect to get the interactive commandline
```
C:/Data/Documents/CSharp/KnowledgeBase/Typin/src/Typin/Examples/InteractiveModeExample/bin/Debug/netcoreapp3.1/InteractiveModeExample.dll [interactive] -h
InteractiveModeExample CLI v3.0.0 {{title}} dotnet InteractiveModeExample.dll {{{description}}} {test}
-- Handling Command
-- Log Command 3
InteractiveModeExample v3.0.0

Description
  Default Command Description

Usage
  dotnet InteractiveModeExample.dll [directive] [command] <values...> [options]

Parameters
* values

Options
  -h|--help             Shows help text.
  --version             Shows version information.

Commands
  book                  List all books in the library.
  pipeline              Prints a middleware pipeline structure in application.
  plot xy               Prints a middleware pipeline structure in application.
  plot xyz
@ quit                  Quits the interactive mode
  services              Prints a list of registered services in application.

You can run `dotnet InteractiveModeExample.dll [command] --help` to show help on a specific command.

Directives
  [!]                   Executes a root or scoped command.
@ [.]                   Removes one command from the scope.
@ [..]                  Resets the scope to default value.
@ [>]                   Sets a scope to command(s).
@ [custom-interactive]  Custom interactive only directive.
  [debug]               Starts a debugging mode. Application will wait for debugger to be attached before proceeding.
  [interactive]         Starts an interactive mode.
  [preview]             The app will short-circuit by printing consumed command line arguments as they were parsed.
-- Finished Command after 133,2201 ms
dotnet InteractiveModeExample.dll: Command finished succesfully.

Process finished with exit code 0.
```

**Expected behavior**
See the help and then get the interactive commandline

**Additional context**
Might be related to #105

![grafik](https://user-images.githubusercontent.com/4518980/98830906-d8d90c80-2432-11eb-8f5c-57206987461d.png)

**Comment by adambajguz** [comment]
Hi, the way `[interactive]` directive works in `3.0.0-dev-00003` is that it is no longer treated as a "special" directive (so actually you can write a `interactive` command not directive to switch modes). 

Currently in InteractiveModeExample the following happens for args `[interactive]`:

1. Application starts in direct mode.
2. Interactive directive is executed (mode change is requested) and command processing stops.
3. Since the mode change was requested Typin initializes interactive mode.

However, when `[interactive] -h` is entered:
1. Application starts in direct mode.
2. `-h` is found and help is printed (in future this may allow for printing different help screen for directives)

I know that this will introduce a very different behavior in Typin, but it will be more consistent and flexible. The newly introduced `ICliMode` interface allows implementing brand custom modes to Typin, like batch mode. Typin 2.x is good and stable, and I use it in my projects, but it is not perfect. I'm also aware that wiki need updating, but since Typin 3.0 is still in development page, I think the best option is to prepare a new wiki page that will describe the differences and a new "philosophy".

Recent code for `*-dev-*` releases can be found on `develop` branch (that is sth I may have forgotten to mention on wiki or in README.md as well - I need to fix this).

PS. Did you know that 3.0 introduces [Typin.Core library](https://www.nuget.org/packages/Typin.Core) ? :)

**Comment by adambajguz** [comment]
**TODO:**

- [ ] Add Typin 3.0 description in a new wiki page
- [ ] Add information about dev releases in wiki and/or README.md.
- [ ] Reevaluate whether it is possible to execute `[interactive] ... some other args ...`.

**Comment by JohannesDeml** [comment]
Hi, thanks a lot for the response, that is some very valuable information!
I have the feeling, that typin has some very smart design decisions and functionality, but right now it is really hard for me, to navigate through its logic.

Getting away from [interactive] to an interactive command sounds very interesting. Looking forward to the new docs, hopefully I will understand the usage better then :)

**Comment by adambajguz** [comment]
#132 will add interactive command and change [interactive] directive behavior to previous

**Comment by JohannesDeml** [comment]
Awesome, thanks a lot for your efforts! I can confirm that `interactive --help` works on the branch 👍

**Comment by adambajguz** [comment]
Changes are available in a prerelease version 3.0.0-dev-00009
